CREATE TABLE CONTACTS (
  CONTACT_ID varchar(36) NOT NULL,
  PRIMARY KEY (CONTACT_ID),
);

CREATE TABLE APPLICATIONS (
  APPLICATION_ID varchar(36) NOT NULL,
  CONTACT_ID varchar(36) NOT NULL,
  DT_CREATED datetime NOT NULL,
  PRODUCT_NAME varchar(50) DEFAULT NULL,
  PRIMARY KEY (APPLICATION_ID),
  FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS(CONTACT_ID)
)